name: Trigger Cloudflare Pages

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  trigger-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Cloudflare Pages deploy hook
        env:
          HOOK_URL: ${{ secrets.CLOUDFLARE_DEPLOY_HOOK_URL }}
        run: |
          if [ -z "$HOOK_URL" ]; then
            echo "CLOUDFLARE_DEPLOY_HOOK_URL not set"
            exit 1
          fi
          curl -X POST "$HOOK_URL" --fail --show-error
